### ISSUE TITLE
TypeError: unhashable type: 'csr_matrix'

### ISSUE THREAD

**Issue by janemd2012** [joachimwolff/scHiCExplorer#13]
Hi There,

Firstly, thanks for the great tools to explore the sc HiC data! I tested scHiCExplorer pipe following the [instruction](https://schicexplorer.readthedocs.io/en/latest/content/Example_analysis.html). I started from [Download of the fastq files](https://schicexplorer.readthedocs.io/en/latest/content/Example_analysis.html#download-of-the-fastq-files). Everything went on very well until [Correction](https://schicexplorer.readthedocs.io/en/latest/content/Example_analysis.html#id8)
The command line used:
`
scHicCorrectMatrices -m nagano2017_normalized.scool -o nagano2017_corrected.scool --threads 20
`
Error messages:(both python3.6 and 3.8 did not work and got the similar error)
_
![image](https://user-images.githubusercontent.com/10444126/192382137-29739c56-8db0-44e6-a6a0-db79b6a3c096.png)
_

Any suggestion on how to fix hashing errors in  [scHiCExplorer](https://github.com/joachimwolff/scHiCExplorer)? Many thanks!

**Comment by janemd2012** [comment]
I googled how to fix this issue.I found a similar issue in a different [SparseLSH](https://github.com/brandonrobertz/SparseLSH/issues/3) years ago.  It mentioned that 

_Mutable data like CSR matrices in python 3+ don't have a hashable type because it can't guarantee a unique mapping. You can either override __hash__ with some key scheme that will ensure a unique mapping based on its data or use a non-hashing data structure._ 

I'm just wondering  anyone can help and show me how to fix the issue? Many thanks.

**Comment by nitishnih** [comment]
I have the same issue in python3.8 at the same step.
```
Traceback (most recent call last):
File "/opt/conda/bin/scHicCorrectMatrices", line 7, in <module>
main()
File "/opt/conda/lib/python3.8/site-packages/schicexplorer/scHicCorrectMatrices.py", line 169, in main
matrixFileHandler.save(args.outFileName, pSymmetric=True, pApplyCorrection=False)
File "/opt/conda/lib/python3.8/site-packages/hicmatrix/lib/matrixFileHandler.py", line 57, in save
self.matrixFile.save(pName, pSymmetric, pApplyCorrection)
File "/opt/conda/lib/python3.8/site-packages/hicmatrix/lib/scool.py", line 46, in save
bins_dict[coolObject.matrixFile.matrixFileName] = bins_data_frame
TypeError: unhashable type: 'csr_matrix'
```
As the last traceback error suggest, the error is in the hicmatrix library [here](https://github.com/deeptools/HiCMatrix/blob/master/hicmatrix/lib/scool.py#L46)

**Comment by orangeSi** [comment]
I get the same error when use schicexplorer v7, finally fixed by change to v5.
