### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'n_jobs'; ValueError: Invalid vmin or vmax

### ISSUE THREAD

**Issue by LHXqwq** [joachimwolff/scHiCExplorer#14]
An error occurs when I run the following code：
scHicClusterMinHash -m raw_normalized.scool --numberOfHashFunctions 1200  --numberOfClusters 7 --clusterMethod kmeans -o clusters_minhash_kmeans.txt --threads 20

2022-12-23 16:06:01.484465: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-23 16:06:01.651899: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-23 16:06:01.651934: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-12-23 16:06:02.484702: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-12-23 16:06:02.484799: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-12-23 16:06:02.484811: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/lihaoxing/miniconda3/bin/scHicClusterMinHash", line 7, in <module>
    main()
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/schicexplorer/scHicClusterMinHash.py", line 299, in main
    cluster_object = KMeans(n_clusters=args.numberOfClusters, random_state=0, n_jobs=args.threads, precompute_distances=True)
TypeError: __init__() got an unexpected keyword argument 'n_jobs'

Another error occurs when I run the following code：
scHicPlotClusterProfiles -m raw_normalized.scool --clusters clusters_svl_spectral.txt -o clusters_svl_spectral.png --dpi 300 --threads 20

Traceback (most recent call last):
  File "/home/lihaoxing/miniconda3/bin/scHicPlotClusterProfiles", line 7, in <module>
    main()
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/schicexplorer/scHicPlotClusterProfiles.py", line 330, in main
    cbar = plt.colorbar()
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2065, in colorbar
    ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kwargs)
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/figure.py", line 1277, in colorbar
    cb = cbar.Colorbar(cax, mappable, **cb_kw)
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 384, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/colorbar.py", line 380, in __init__
    self._reset_locator_formatter_scale()
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/colorbar.py", line 1165, in _reset_locator_formatter_scale
    self._process_values()
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/colorbar.py", line 1099, in _process_values
    self.norm.vmin, self.norm.vmax = mtransforms.nonsingular(
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/colors.py", line 1249, in vmin
    self._changed()
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/colors.py", line 1277, in _changed
    self.callbacks.process('changed')
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 312, in process
    self.exception_handler(exc)
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 96, in _exception_printer
    raise exc
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 307, in process
    func(*args, **kwargs)
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/image.py", line 326, in changed
    cm.ScalarMappable.changed(self)
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/cm.py", line 683, in changed
    self.callbacks.process('changed', self)
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 312, in process
    self.exception_handler(exc)
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 96, in _exception_printer
    raise exc
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 307, in process
    func(*args, **kwargs)
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/colorbar.py", line 495, in update_normal
    self._draw_all()
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/colorbar.py", line 530, in _draw_all
    self._process_values()
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/colorbar.py", line 1103, in _process_values
    b = self.norm.inverse(b)
  File "/home/lihaoxing/miniconda3/lib/python3.9/site-packages/matplotlib/colors.py", line 1708, in inverse
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax

**Comment by joachimwolff** [comment]
Please check if your installed dependencies have the same version number as the ones listed in requirements.txt. I fear that some dependency updated their API and that leads to that it is broken now.
